pull_request_rules:
  - name: Automatically merge into master from dependabot (github's dependency updater)
    conditions:
      - base=master
      - status-success=netlify/armory-docs/deploy-preview 
    actions:
      merge:
        method: squash
        strict: smart
      label:
        add: ["auto merged"]
