apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-index-html
data:
  index.html: |
    <html>
    <body bgcolor=blue>
    <marquee behavior=alternate>
    <font face=arial size=6 color=white>
    !!! Welcome to Nginx Blue Deployment !!!
    </font>
    </marquee>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: blue
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html # mount index.html to /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
              name: index-html
      volumes:
        - name: index-html
          configMap:
            name: blue-index-html # place ConfigMap `index-html` on /usr/share/nginx/html/index.html
            items:
              - key: index.html
                path: index.html
