apiVersion: v1
kind: ConfigMap
metadata:
  name: green-index-html
data:
  index.html: |
    <html>
    <body bgcolor=green>
    <marquee behavior=alternate>
    <font face=arial size=6 color=white>
    !!! Welcome to Nginx Green Deployment !!!
    </font>
    </marquee>
    </body>
    </html>

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      version: green
  template:
    metadata:
      labels:
        app: nginx
        version: green
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html # mount index.html to /usr/share/nginx/html/index.html
              subPath: index.html
              readOnly: true
              name: index-html
      volumes:
        - name: index-html
          configMap:
            name: green-index-html # place ConfigMap `index-html` on /usr/share/nginx/html/index.html
            items:
              - key: index.html
                path: index.html
