apiVersion: v1
data:
  armory-agent.yaml: "kubernetes:\n  accounts: []\n  # Add your accounts here, /kubeconfigfiles
    is the path where kubeconfig files added\n  # to kustomization.yaml are mounted.\n#
    \ - kubeconfigFile: /kubeconfigfiles/kubecfg-test.yml\n#    name: account1\n#
    \   metrics: false\n#    kinds: []\n#    omitKinds: []\n    # You can add all
    the other fields from clouddriver settings, they'll be ignored.\n\nclouddriver:\n
    \ grpc: spin-clouddriver:9091\n\nserver:\n  port: 8082\n  \nprometheus:\n  enabled:
    true\n  # port: 8008\n"
kind: ConfigMap
metadata:
  name: armory-agent-config-7f24d6gtfg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-armory-agent
  name: armory-agent-metrics
spec:
  ports:
  - name: metrics
    port: 8008
    protocol: TCP
    targetPort: metrics
  selector:
    app: spin
    cluster: spin-armory-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin
    app.kubernetes.io/name: armory-agent
    app.kubernetes.io/part-of: spinnaker
    cluster: spin-armory-agent
  name: spin-armory-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-armory-agent
  template:
    metadata:
      labels:
        app: spin
        app.kubernetes.io/name: armory-agent
        app.kubernetes.io/part-of: spinnaker
        cluster: spin-armory-agent
    spec:
      containers:
      - image: armory/armory-agent:0.2.0-rc.54
        imagePullPolicy: IfNotPresent
        name: armory-agent
        ports:
        - containerPort: 8082
          name: health
          protocol: TCP
        - containerPort: 8008
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: health
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/armory/config
          name: volume-armory-agent-config
        - mountPath: /kubeconfigfiles
          name: volume-armory-agent-kubeconfigs
      restartPolicy: Always
      volumes:
      - configMap:
          name: armory-agent-config-7f24d6gtfg
        name: volume-armory-agent-config
      - name: volume-armory-agent-kubeconfigs
        secret:
          defaultMode: 420
          secretName: kubeconfigs-secret
