name: Automerge RC release notes

on:
  pull_request:
    paths:
      - 'content/en/continuous-deployment/release-notes/rn-prerelease-armory-spinnaker/**'

jobs:
  automerge:
    name: auto-merge rc release notes PR
    if: ${{ github.event.pull_request.user.login == 'armory-astrolabe' && contains(github.event.pull_request.labels.*.name, 'automerge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR label
        uses: NathanielHill/check-pr-label-action@v4.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          valid-labels: 'automerge, releaseNotesUpdate'
      - name: Enable automerge in PR
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: "${{ secrets.ASTROLABE_GITHUB_TOKEN }}"