name: HTMLTEST

# Run this workflow every time a new commit pushed to your repository
on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  htmltest:
    # Name the Job
    name: Run HTMLTEST link checker
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@master

      # Runs the HTMLTEST action
      - name: Run HTMLTEST
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}